#############################################################################
# Makefile for building: projectHTML5
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue Mar 20 15:15:25 2012
# Project:  projectHTML5.pro
# Template: app
# Command: /home/tomieq/QtSDK/Simulator/Qt/gcc/bin/qmake -spec ../../../QtSDK/Simulator/Qt/gcc/mkspecs/linux-g++ -o Makefile projectHTML5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../QtSDK/Simulator/Qt/gcc/mkspecs/linux-g++ -I. -I../../../QtSDK/Simulator/Qt/gcc/include/QtCore -I../../../QtSDK/Simulator/Qt/gcc/include/QtGui -I../../../QtSDK/Simulator/Qt/gcc/include/QtWebKit -I../../../QtSDK/Simulator/Qt/gcc/include -I../../../QtSDK/Simulator/QtMobility/gcc/include/QtSensors -I/home/tomieq/QtSDK/Simulator/QtMobility/gcc/include/QtMobilitySimulator -I../../../QtSDK/Simulator/QtMobility/gcc/include -I../../../QtSDK/Simulator/QtMobility/gcc/include/QtMobility -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/tomieq/QtSDK/Simulator/Qt/gcc/lib -Wl,-rpath,/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/tomieq/QtSDK/Simulator/Qt/gcc/lib -L/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib -lQtMobilitySimulator -lQtSensors -lQtWebKit -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/tomieq/QtSDK/Simulator/Qt/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		viewloader.cpp \
		sensor.cpp moc_viewloader.cpp \
		moc_sensor.cpp
OBJECTS       = main.o \
		viewloader.o \
		sensor.o \
		moc_viewloader.o \
		moc_sensor.o
DIST          = ../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/g++.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/mobility.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/include_source_dir.prf \
		projectHTML5.pro
QMAKE_TARGET  = projectHTML5
DESTDIR       = 
TARGET        = projectHTML5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projectHTML5.pro  ../../../QtSDK/Simulator/Qt/gcc/mkspecs/linux-g++/qmake.conf ../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/g++.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/mobility.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/include_source_dir.prf \
		/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib/libQtMobilitySimulator.prl \
		/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib/libQtSensors.prl
	$(QMAKE) -spec ../../../QtSDK/Simulator/Qt/gcc/mkspecs/linux-g++ -o Makefile projectHTML5.pro
../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/g++.conf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/common/linux.conf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_pre.prf:
deployment.pri:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/release.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/mobility.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Simulator/Qt/gcc/mkspecs/features/include_source_dir.prf:
/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib/libQtMobilitySimulator.prl:
/home/tomieq/QtSDK/Simulator/QtMobility/gcc/lib/libQtSensors.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Simulator/Qt/gcc/mkspecs/linux-g++ -o Makefile projectHTML5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/projectHTML51.0.0 || $(MKDIR) .tmp/projectHTML51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/projectHTML51.0.0/ && $(COPY_FILE) --parents viewloader.h sensor.h .tmp/projectHTML51.0.0/ && $(COPY_FILE) --parents main.cpp viewloader.cpp sensor.cpp .tmp/projectHTML51.0.0/ && (cd `dirname .tmp/projectHTML51.0.0` && $(TAR) projectHTML51.0.0.tar projectHTML51.0.0 && $(COMPRESS) projectHTML51.0.0.tar) && $(MOVE) `dirname .tmp/projectHTML51.0.0`/projectHTML51.0.0.tar.gz . && $(DEL_FILE) -r .tmp/projectHTML51.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_viewloader.cpp moc_sensor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_viewloader.cpp moc_sensor.cpp
moc_viewloader.cpp: viewloader.h
	/home/tomieq/QtSDK/Simulator/Qt/gcc/bin/moc $(DEFINES) $(INCPATH) viewloader.h -o moc_viewloader.cpp

moc_sensor.cpp: sensor.h
	/home/tomieq/QtSDK/Simulator/Qt/gcc/bin/moc $(DEFINES) $(INCPATH) sensor.h -o moc_sensor.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp viewloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

viewloader.o: viewloader.cpp viewloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewloader.o viewloader.cpp

sensor.o: sensor.cpp sensor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensor.o sensor.cpp

moc_viewloader.o: moc_viewloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewloader.o moc_viewloader.cpp

moc_sensor.o: moc_sensor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensor.o moc_sensor.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/projectHTML5/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/projectHTML5/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/projectHTML5/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/projectHTML5/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/projectHTML5/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/projectHTML5/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

